services:
  db:
    image: postgres:14-alpine
    container_name: proyectateucn_db
    restart: always
    environment:
      POSTGRES_USER: UsuarioDesintegrador
      POSTGRES_PASSWORD: ericRoss
      POSTGRES_DB: proyecciones_db
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data